---
name: "deploy"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t frc-emotion/website:latest .
      - name: Push to Dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ssh://dokku@team2658.org:22/website
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      
